on:
  push:
    branches:
      - CRAN
      - main
    paths:
      - README.Rmd

name: Render-README

jobs:
  render-readme:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1

    # Install packages needed
    - name: install required packages
      run: |
        install.packages("remotes")
        remotes::install_cran("rmarkdown")
        remotes::install_local(".")

    # Render READEME.md using rmarkdown
    - name: render README
      run: Rscript -e 'rmarkdown::render("README.Rmd")'

    # Commit and push files to github
    - name: commit rendered README
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add README.md man/figures/README-*
        git commit -m "Re-build README.md" || echo "No changes to commit"
        git push origin || echo "No changes to commit"
